# Generated by Django 2.2.7 on 2019-11-15 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20191115_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_roll',
            field=models.IntegerField(unique=True),
        ),
    ]
