# Generated by Django 2.2.7 on 2019-11-24 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSemester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentSemester', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student_classes.StudentClass')),
            ],
        ),
    ]
