# Generated by Django 2.2.7 on 2019-11-24 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_classes', '0004_auto_20191124_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsemester',
            name='StudentSemester',
            field=models.IntegerField(choices=[('1-1', '1-1'), ('1-2', '1-2'), ('2-1', '2-1'), ('2-2', '2-2'), ('3-1', '3-1'), ('3-2', '3-2'), ('4-1', '4-1'), ('4-2', '4-2')]),
        ),
    ]
