# Generated by Django 2.2.7 on 2019-11-24 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0009_remove_subjectcombination_subject_semester'),
        ('student_classes', '0006_auto_20191124_1651'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentSemester',
        ),
    ]
