# Generated by Django 2.2.7 on 2019-11-24 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='subject_credits',
            field=models.IntegerField(default=2),
        ),
    ]
