# Generated by Django 2.2.7 on 2019-11-24 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_subject_subject_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='subject_semester',
            field=models.CharField(choices=[('1-1', '1-1'), ('1-2', '1-2'), ('2-1', '2-1'), ('2-2', '2-2'), ('3-1', '3-1'), ('3-2', '3-2'), ('4-1', '4-1'), ('4-2', '4-2')], default='1-1', max_length=10),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_grade',
            field=models.CharField(choices=[('O', 'O'), ('A+', 'A+'), ('A', 'A'), ('B+', 'B+'), ('C', 'C'), ('F', 'F')], default='O', max_length=10),
        ),
    ]
