# Generated by Django 2.2.7 on 2019-11-24 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0005_subjectcombination_subject_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectcombination',
            name='subject_semester',
            field=models.ForeignKey(default='1-1', on_delete=django.db.models.deletion.CASCADE, to='student_classes.StudentSemester'),
        ),
    ]
