# Generated by Django 2.2.7 on 2019-11-24 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0006_auto_20191124_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subject_semester',
            field=models.CharField(choices=[('1_1', '1_1'), ('1_2', '1_2'), ('2_1', '2_1'), ('2_2', '2_2'), ('3_1', '3_1'), ('3_2', '3_2'), ('4_1', '4_1'), ('4_2', '4_2')], default='1-1', max_length=10),
        ),
        migrations.AlterField(
            model_name='subjectcombination',
            name='subject_semester',
            field=models.ForeignKey(default='1_1', on_delete=django.db.models.deletion.CASCADE, to='student_classes.StudentSemester'),
        ),
    ]
