# Generated by Django 2.2.7 on 2019-11-24 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0009_remove_subjectcombination_subject_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subject_semester',
            field=models.CharField(choices=[('1_1', '1_1'), ('1_2', '1_2'), ('2_1', '2_1'), ('2_2', '2_2'), ('3_1', '3_1'), ('3_2', '3_2'), ('4_1', '4_1'), ('4_2', '4_2')], default='1_1', max_length=10),
        ),
    ]
