# Generated by Django 2.2.7 on 2019-11-24 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0010_auto_20191124_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subject_semester',
            field=models.CharField(choices=[('1-1', '1-1'), ('1-2', '1-2'), ('2-1', '2-1'), ('2-2', '2-2'), ('3-1', '3-1'), ('3-2', '3-2'), ('4-1', '4-1'), ('4-2', '4-2')], default='1-1', max_length=10),
        ),
    ]
